# Generated by Django 5.2.4 on 2026-08-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_studentinvoice_studentpayment'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.studentinvoice'),
        ),
        migrations.AlterUniqueTogether(
            name='studentinvoice',
            unique_together={('student', 'session')},
        ),
    ]
