# Generated by Django 5.2.4 on 2026-08-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2026/2027 — must match Student.session exactly.', max_length=20, unique=True)),
                ('registration_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, help_text="Must match a student's Level exactly, e.g. ND I, ND II.", max_length=30),
        ),
    ]
