# Generated by Django 5.2.4 on 2026-08-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_result_ca_score_result_exam_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='breakdown_note',
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text="Optional group heading shown above this row, e.g. 'First Semester', 'Second Semester'.", max_length=50)),
                ('label', models.CharField(help_text='e.g. Tuition/School Fees', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank for a variable charge (shown via the Note field instead, e.g. 'To Be Announced').", max_digits=10, null=True)),
                ('note', models.CharField(blank=True, help_text="Shown instead of an amount when Amount is left blank, e.g. 'To Be Announced' or 'As Applicable'.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='students.feestructure')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
