# Generated by Django 5.2.4 on 2026-08-26 10:15

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_we_are', django_ckeditor_5.fields.CKEditor5Field(default='<p>Hamdaan International College of Health, Science and Technology is committed to developing competent, ethical and innovative professionals equipped to serve communities and contribute meaningfully to the healthcare and technology sectors.</p>')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('mission', django_ckeditor_5.fields.CKEditor5Field(default='<p>To provide accessible, practical and industry-relevant health science and technology education that prepares graduates to deliver excellent service to their communities and advance in their chosen careers.</p>')),
                ('vision', django_ckeditor_5.fields.CKEditor5Field(default='<p>To be a leading health, science and technology institution in West Africa, recognised for producing skilled, ethical and innovative professionals who transform lives and communities.</p>')),
                ('principal_name', models.CharField(default='Dr. Amina Yusuf', max_length=100)),
                ('principal_title', models.CharField(default='Principal / Chief Executive', max_length=100)),
                ('principal_message', django_ckeditor_5.fields.CKEditor5Field(default='<p>At Hamdaan International College, we believe education is the most powerful tool for transforming lives and communities. Our commitment goes beyond the classroom — we are building a generation of health, science and technology professionals who are skilled, compassionate and ready to serve.</p>')),
                ('principal_photo', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-star', max_length=50)),
                ('title', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('head_name', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='fa-building-columns', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('category', models.CharField(default='Academics', max_length=60)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='facilities/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(default='Academics', max_length=60)),
                ('author', models.CharField(default='Public Relations Unit', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('excerpt', models.TextField(max_length=300)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Hamdaan International College', max_length=150)),
                ('site_short_name', models.CharField(default='HIC', help_text='Shown in the compact navbar lockup.', max_length=20)),
                ('tagline', models.CharField(default='Empowering Careers. Transforming Lives. Building a Healthier Future.', max_length=200)),
                ('marketing_phrase', models.CharField(blank=True, default='Build Skills. Save Lives. Impact Communities.', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Leave blank to use the default crest.', null=True, upload_to='branding/')),
                ('announcement_text', models.CharField(blank=True, default='2026/2027 Admission is Now Open — Apply Today', max_length=200)),
                ('announcement_link_text', models.CharField(blank=True, default='Apply Now', max_length=50)),
                ('show_announcement_bar', models.BooleanField(default=True)),
                ('admission_session', models.CharField(default='2026/2027', max_length=20)),
                ('admission_open', models.BooleanField(default=True)),
                ('hero_badge_text', models.CharField(default='2026/2027 Academic Session — Admission Open', max_length=100)),
                ('hero_headline', models.CharField(default='Build Your Future in Health, Science & Technology.', max_length=200)),
                ('hero_highlight', models.CharField(blank=True, default='Health, Science & Technology.', help_text='The portion of the headline shown in gold — must match text within the headline.', max_length=100)),
                ('hero_subtext', models.TextField(default='At Hamdaan International College, we equip students with practical knowledge, professional skills and real-world experience to build meaningful careers and contribute to healthier communities.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hero_primary_cta_text', models.CharField(default='Apply for Admission', max_length=50)),
                ('hero_secondary_cta_text', models.CharField(default='Explore Programmes', max_length=50)),
                ('who_we_are_short', models.TextField(default='Hamdaan International College of Health, Science and Technology is committed to developing competent, ethical and innovative professionals equipped to serve communities and contribute to the healthcare and technology sectors.')),
                ('address_line', models.CharField(default='No. 20 Hayin Bako, Sabon-gari, Zaria, Kaduna State, Nigeria.', max_length=250)),
                ('phone_1', models.CharField(default='09063447124', max_length=30)),
                ('phone_2', models.CharField(blank=True, default='09122641898', max_length=30)),
                ('phone_3', models.CharField(blank=True, default='0912 630 2484', max_length=30)),
                ('email', models.EmailField(default='hamdaanglobalmail@gmail.com', max_length=254)),
                ('office_hours', models.CharField(default='Monday – Friday: 8:00 AM – 5:00 PM · Saturday: 9:00 AM – 1:00 PM', max_length=200)),
                ('facebook_url', models.URLField(blank=True, default='#')),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
                ('linkedin_url', models.URLField(blank=True, default='#')),
                ('whatsapp_number', models.CharField(blank=True, default='2349063447124', help_text='International format, no plus sign — used for the floating WhatsApp button.', max_length=30)),
                ('footer_about', models.TextField(default='Empowering careers, transforming lives and building a healthier future through practical, industry-relevant health science education.')),
                ('footer_cta_heading', models.CharField(default='Your Future in Health, Science & Technology Starts Here.', max_length=200)),
                ('admission_requirement_note', models.TextField(default="Five (5) O'Level credit passes including English Language, Mathematics, Chemistry, Physics and Biology.")),
                ('admission_requirement_disclaimer', models.TextField(default='This is sample / general admission information provided for demonstration purposes. Specific programmes may have additional requirements — please contact the Admissions Office for full details.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('value', models.PositiveIntegerField(help_text='Numeric value the counter animates up to, e.g. 1200.')),
                ('suffix', models.CharField(blank=True, default='+', help_text="Shown after the number, e.g. '+' or '%'.", max_length=5)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class, e.g. fa-user-graduate.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentLifeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-people-group', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Student Life Activities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-star', help_text='Font Awesome class, e.g. fa-award.', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.gallerycategory')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('ND', 'National Diploma'), ('PD', 'Professional Diploma'), ('CERT', 'Professional Certification')], default='ND', max_length=6)),
                ('duration', models.CharField(default='2 Years', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programmes/')),
                ('description', models.TextField()),
                ('requirement', models.TextField(default="Five (5) O'Level credit passes including English Language, Mathematics, Chemistry, Physics and Biology.")),
                ('careers', models.TextField(blank=True, default='Government Health Facilities\nPrivate Hospitals & Clinics\nNGOs & Community Health Programmes\nFurther Professional Studies', help_text='One career opportunity per line.')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this programme prominently on the Programmes page.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to='website.department')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=60)),
                ('lga', models.CharField(max_length=80)),
                ('preferred_session', models.CharField(default='2026/2027', max_length=20)),
                ('previous_school', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=60)),
                ('exam_type', models.CharField(max_length=20)),
                ('exam_number', models.CharField(max_length=40)),
                ('exam_year', models.CharField(max_length=10)),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='applications/passports/')),
                ('olevel_result', models.FileField(blank=True, null=True, upload_to='applications/olevel/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='applications/birth/')),
                ('identification_document', models.FileField(blank=True, null=True, upload_to='applications/id/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='website.programme')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
