# Generated by Django 5.2.4 on 2026-08-31 08:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='principal_bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', help_text="A short biography — shown under the welcome message on the About page and the homepage's Founder & CEO section."),
        ),
    ]
