# Generated by Django 5.2.4 on 2026-08-31 08:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutcontent_principal_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(default='Zaria, Kaduna State', max_length=150)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=20)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('requirements', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('deadline', models.DateField(help_text='Applications close at the end of this date — the posting is then automatically hidden from the public Careers page, no manual step needed.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to close a posting early, before its deadline.')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='job_applications/')),
                ('status', models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='website.jobposting')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
