# Generated by Django 5.2.4 on 2026-08-26 12:12

import admissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_delete_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='e.g. 2026/2027', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one cycle can be active — activating this one deactivates any other.')),
                ('fee', models.DecimalField(decimal_places=2, help_text='Application fee for this session, in Naira.', max_digits=10)),
                ('opens_at', models.DateTimeField(blank=True, help_text='Optional — leave blank to rely on the active toggle alone.', null=True)),
                ('closes_at', models.DateTimeField(blank=True, help_text='Optional — leave blank to rely on the active toggle alone.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission Cycle',
                'verbose_name_plural': 'Admission Cycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(default=admissions.models.generate_application_number, editable=False, max_length=20, unique=True)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('state_of_origin', models.CharField(blank=True, max_length=60)),
                ('lga', models.CharField(blank=True, max_length=80, verbose_name='Local Government Area')),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('religion', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('alt_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_relationship', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Other', 'Other')], max_length=20)),
                ('guardian_occupation', models.CharField(blank=True, max_length=150)),
                ('guardian_address', models.CharField(blank=True, max_length=250)),
                ('guardian_phone', models.CharField(blank=True, max_length=30)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('qualification_obtained', models.CharField(blank=True, max_length=100)),
                ('qualification_year', models.CharField(blank=True, max_length=10)),
                ('english_grade', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('english_exam_body', models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NABTEB', 'NABTEB')], max_length=10)),
                ('english_year', models.CharField(blank=True, max_length=10)),
                ('maths_grade', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2, verbose_name='Mathematics Grade')),
                ('maths_exam_body', models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NABTEB', 'NABTEB')], max_length=10, verbose_name='Mathematics Examination Body')),
                ('maths_year', models.CharField(blank=True, max_length=10, verbose_name='Mathematics Year')),
                ('chemistry_grade', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('chemistry_exam_body', models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NABTEB', 'NABTEB')], max_length=10)),
                ('chemistry_year', models.CharField(blank=True, max_length=10)),
                ('physics_grade', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('physics_exam_body', models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NABTEB', 'NABTEB')], max_length=10)),
                ('physics_year', models.CharField(blank=True, max_length=10)),
                ('biology_grade', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('biology_exam_body', models.CharField(blank=True, choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('NABTEB', 'NABTEB')], max_length=10)),
                ('biology_year', models.CharField(blank=True, max_length=10)),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to=admissions.models.application_document_path)),
                ('olevel_result', models.FileField(blank=True, null=True, upload_to=admissions.models.application_document_path)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to=admissions.models.application_document_path)),
                ('identification_document', models.FileField(blank=True, null=True, upload_to=admissions.models.application_document_path)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('is_submitted', models.BooleanField(default=False, help_text='False while still being filled in after payment — only True once finally submitted.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.admissioncycle')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='website.programme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
