# Generated by Django 5.2.4 on 2026-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('full_access', 'Full Access (Super Admin)'), ('exam_officer', 'Exam Officer'), ('registrar', 'Registrar'), ('bursar', 'Bursar')], default='full_access', max_length=30),
        ),
    ]
