# Generated by Django 5.2.4 on 2026-08-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('full_access', 'Full Access (Super Admin)'), ('exam_officer', 'Exam Officer'), ('registrar', 'Registrar'), ('bursar', 'Bursar'), ('academic_secretary', 'Academic Secretary')], default='full_access', max_length=30),
        ),
    ]
